apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-app
  region: eu-west-2

nodeGroups:
  - name: node-group-1
    instanceType: t2.medium
    desiredCapacity: 3
    ssh:
      allow: false

